### ISSUE TITLE
guys could you stop putting your name as an author if you didnt actually contribute to the page thanks

### ISSUE THREAD

**Issue by vasharm2** [GeneralOneill/NEOSA#16]

**Comment by GeneralOneill** [comment]
Alright let me be clear. You put your name as the author if you actually coded your own code to the page! Not copy and pasting pre-made templates. And yes Vik, I am in fact the only one that has done any original coding to the templates, I am the one finalized the navigation bars, I am the one that restructured the lay outs. So you and Nathan don't even deserve to put your name as the author. Because neither of you two has done ANY ORIGINAL CODING!
